OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = no
QMK_SETTINGS = no
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

# VIALRGB_ENABLE = yes # vial.json > "lighting": "vialrgb",
# RGB_MATRIX_ENABLE = yes
# DYNAMIC_MACRO_ENABLE = yes
